### ISSUE TITLE
Lazy loading while running portal

### ISSUE THREAD

**Issue by EvanBurbidge** [egoisticum/single-spa-vue-router#1]
First of all great work, I'd of been stuck for weeks with this if it weren't for your work. Just one quick comment / question, in singleSpaEntry I see you're importing the components from your views folder, i've also noticed that if I don't do this I get a 404 error from the portal saying that those chunks aren't found. Are these chunks still being lazy loaded or in order to work with the portal do we need to eagerly load them? 

Thanks!

**Comment by snowlotus** [comment]
@EvanBurbidge i have the same problem with you,have you ever solved it or not?

**Comment by thewebuiguy** [comment]
@snowlotus  https://github.com/EvanBurbidge/single-spa-lazy-load-test/tree/master/vue-test/src you can take a look in here, with the new single-spa-vue you can lazy load your App.vue which allows you to dynamically set the public path :)
